# render.yaml - Free tier setup for Vue + Node + Postgres in ONE repo

services:
  - type: web
    name: backend
    runtime: node
    repo: https://github.com/thedavids/your-project
    branch: main
    rootDir: server
    plan: free
    buildCommand: npm ci
    startCommand: npm start
    envVars:
      # Environment
      - key: NODE_ENV
        value: development

      # Google & Facebook auth
      - key: GOOGLE_CLIENT_ID
        value: "TEMP_GOOGLE_CLIENT_ID"
      - key: GOOGLE_CLIENT_SECRET
        value: "TEMP_GOOGLE_CLIENT_SECRET"
      - key: GOOGLE_MAP_API
        value: "TEMP_GOOGLE_MAP_API"
      - key: FACEBOOK_APP_ID
        value: "TEMP_FACEBOOK_APP_ID"
      - key: FACEBOOK_APP_SECRET
        value: "TEMP_FACEBOOK_APP_SECRET"

      # Cookies & JWT
      - key: COOKIE_DOMAIN_PROD
        value: ".yourwebsite.com"
      - key: JWT_SECRET
        value: "TEMP_JWT_SECRET"
      - key: REFRESH_TOKEN_SECRET
        value: "TEMP_REFRESH_SECRET"
      - key: EMAIL_SECRET_ACTIVATION_SECRET
        value: "TEMP_EMAIL_ACTIVATION_SECRET"

      # Email (Resend)
      - key: EMAIL_RESEND_API_KEY
        value: "TEMP_RESEND_API_KEY"
      - key: EMAIL_FROM
        value: "noreply@example.com"

      # Database (both full URL + individual parts)
      - key: DATABASE_URL
        fromDatabase:
          name: database
          property: connectionStringInternal
      - key: DB_HOST
        value: "TEMP_DB_HOST"
      - key: DB_PORT
        value: "5432"
      - key: DB_NAME
        value: "TEMP_DB_NAME"
      - key: DB_USER
        value: "TEMP_DB_USER"
      - key: DB_PASSWORD
        value: "TEMP_DB_PASSWORD"

      # Frontend/backend URLs
      - key: FE_URL
        value: "http://localhost:5173"
      - key: API_URL
        value: "http://localhost:3000"

      # AWS S3
      - key: AWS_ACCESS_KEY_ID
        value: "TEMP_AWS_KEY"
      - key: AWS_SECRET_ACCESS_KEY
        value: "TEMP_AWS_SECRET"
      - key: S3_BUCKET
        value: "ineedhelps-uploads-prod"
      - key: S3_REGION
        value: "us-east-1"
      - key: S3_PUBLIC_BASE_URL
        value: "https://ineedhelps-uploads-prod.s3.amazonaws.com"

  - type: static
    name: frontend
    repo: https://github.com/thedavids/your-project
    branch: main
    rootDir: client
    plan: free
    buildCommand: npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"

databases:
  - name: database
    plan: free
