# render.yaml - Free tier setup for Vue + Node + Postgres in ONE repo

services:
  - type: web
    name: backend
    runtime: node
    repo: https://github.com/your-org/repo
    branch: main
    rootDir: server
    plan: free
    buildCommand: npm ci
    startCommand: npm start
    envVars:
      # Environment
      - key: NODE_ENV
        value: production

      # Google & Facebook auth
      - key: GOOGLE_CLIENT_ID
        value: "TEMP_GOOGLE_CLIENT_ID"
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        value: "TEMP_GOOGLE_CLIENT_SECRET"
        sync: false
      - key: GOOGLE_MAP_API
        value: "TEMP_GOOGLE_MAP_API"
        sync: false
      - key: FACEBOOK_APP_ID
        value: "TEMP_FACEBOOK_APP_ID"
        sync: false
      - key: FACEBOOK_APP_SECRET
        value: "TEMP_FACEBOOK_APP_SECRET"
        sync: false

      # Cookies & JWT
      - key: COOKIE_DOMAIN_PROD
        value: ".yourwebsite.com"
        sync: false
      - key: JWT_SECRET
        value: "TEMP_JWT_SECRET"
        sync: false
      - key: REFRESH_TOKEN_SECRET
        value: "TEMP_REFRESH_SECRET"
        sync: false
      - key: EMAIL_SECRET_ACTIVATION_SECRET
        value: "TEMP_EMAIL_ACTIVATION_SECRET"
        sync: false

      # Email (Resend)
      - key: EMAIL_RESEND_API_KEY
        value: "TEMP_RESEND_API_KEY"
        sync: false
      - key: EMAIL_FROM
        value: "noreply@example.com"
        sync: false

      # Database individual parts
      - key: DB_HOST
        value: "TEMP_DB_HOST"
        sync: false
      - key: DB_PORT
        value: "5432"
        sync: false
      - key: DB_NAME
        value: "TEMP_DB_NAME"
        sync: false
      - key: DB_USER
        value: "TEMP_DB_USER"
        sync: false
      - key: DB_PASSWORD
        value: "TEMP_DB_PASSWORD"
        sync: false

      # Frontend/backend URLs
      - key: FE_URL
        value: "http://localhost:5173"
        sync: false
      - key: API_URL
        value: "http://localhost:3000"
        sync: false

      # AWS S3
      - key: AWS_ACCESS_KEY_ID
        value: "TEMP_AWS_KEY"
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        value: "TEMP_AWS_SECRET"
        sync: false
      - key: S3_BUCKET
        value: "ineedhelps-uploads-prod"
        sync: false
      - key: S3_REGION
        value: "us-east-1"
        sync: false
      - key: S3_PUBLIC_BASE_URL
        value: "https://ineedhelps-uploads-prod.s3.amazonaws.com"
        sync: false

  - type: web
    name: frontend
    runtime: static
    repo: https://github.com/your-org/repo
    branch: main
    rootDir: client
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"

databases:
  - name: database
    plan: free
